steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.admin-api
      - -t
      - us-central1-docker.pkg.dev/fotovitoria/photo-vitoria/admin-api:latest
      - .

images:
  - us-central1-docker.pkg.dev/fotovitoria/photo-vitoria/admin-api:latest
